<a href="https://colab.research.google.com/github/freddy-7/TI3002C/blob/main/9_Regresion_Logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [31]:
#Cargar archivo csv
df= pd.read_csv("DataAnalytics.csv")
df.head()

Administrador  Usuario  botón correcto  tiempo de interacción mini juego  \
0       nicolas  nicolas             1.0               5.399169   Despegue   
1       nicolas  nicolas             0.0               1.283400   Despegue   
2       nicolas  nicolas             1.0               2.700226   Despegue   
3       nicolas  nicolas             0.0               3.050262   Despegue   
4       nicolas  nicolas             0.0               4.750256   Despegue   

   número de interacción color presionado  dificultad             fecha  \
0                    1.0             blue  Episodio 1  25/01/2024 09:26   
1                    2.0           violet  Episodio 1  25/01/2024 09:26   
2                    3.0            green  Episodio 1  25/01/2024 09:26   
3                    4.0            green  Episodio 1  25/01/2024 09:26   
4                    5.0            green  Episodio 1  25/01/2024 09:26   

   Juego  auto push  tiempo de lección  tiempo de sesión  
0  Astro        0.0                0.0               0.0  
1  Astro        0.0                0.0               0.0  
2  Astro        0.0                0.0               0.0  
3  Astro        0.0                0.0               0.0  
4  Astro        0.0                0.0               0.0

In [32]:
#Rellenamos nulos
df =df.fillna(method="bfill")
df =df.fillna(method="ffill")


C:\Users\alfre\AppData\Local\Temp\ipykernel_10932\374832835.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="bfill")
C:\Users\alfre\AppData\Local\Temp\ipykernel_10932\374832835.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="ffill")


In [33]:
#Analizar categorias de una columna
Categorias_Juego = df.groupby(['Juego'])['Juego'].count()
Categorias_Juego

Juego
Astro      3799
Cadetes    2066
Name: Juego, dtype: int64

In [34]:
#Declaramos las variables dependientes e independientes para la regresión Logística
Vars_Indep= df[['número de interacción']]
Var_Dep= df['Juego']

In [35]:
#Redefinimos las variables 
X= Vars_Indep
y= Var_Dep

In [36]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [37]:
#Se escalan todos los datos
escalar = StandardScaler()

In [38]:
#Para realizar el escalamiento de las variables “X” tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [39]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [40]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\alfre\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sklearn\\utils\\_repr_html\\estimator.js'

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\alfre\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sklearn\\utils\\_repr_html\\estimator.js'

LogisticRegression()

In [41]:
#Realizamos una predicción
y_pred = algoritmo.predict(X_test) 
y_pred

array(['Astro', 'Astro', 'Astro', ..., 'Astro', 'Astro', 'Astro'],
      shape=(1760,), dtype=object)

In [42]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[1162    0]
 [ 598    0]]


In [43]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="binary", pos_label="Cadetes")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.0


c:\Users\alfre\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [44]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.6602272727272728


In [45]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Astro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
1.0


In [46]:
# el puntaje F1 que es una combinación entre la precisión y la sensibilidad, para esto importamos f1_score.
#Calculo el Puntaje F1 del modelo
from sklearn.metrics import f1_score

puntajef1 = f1_score(y_test, y_pred, average="binary", pos_label="Astro")
print('Puntaje F1 del modelo:')
print(puntajef1)

Puntaje F1 del modelo:
0.7953456536618754


***Método 1 Reponderación de las Clases***

In [47]:
#Reponderación de las clases
algoritmo_Pond = LogisticRegression(class_weight='balanced')
algoritmo_Pond.fit(X_train, y_train)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\alfre\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sklearn\\utils\\_repr_html\\estimator.js'

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\alfre\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\sklearn\\utils\\_repr_html\\estimator.js'

LogisticRegression(class_weight='balanced')

In [48]:
#Realizamos una predicción
y_pred_pond = algoritmo_Pond.predict(X_test) 
y_pred_pond

array(['Cadetes', 'Cadetes', 'Cadetes', ..., 'Cadetes', 'Cadetes',
       'Astro'], shape=(1760,), dtype=object)

In [49]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[390 772]
 [138 460]]


In [50]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Astro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.7386363636363636


In [51]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred_pond)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.48295454545454547


In [52]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Astro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.33562822719449226


***Método 2 Submuestreo o Sobremuestreo***

In [ ]:
pip install imblearn

In [57]:
#Aplicamos la técnica de sobremuestreo (oversampling)
from imblearn.over_sampling import SMOTE

ImportError: cannot import name '_deprecate_Xt_in_inverse_transform' from 'sklearn.utils.deprecation' (c:\Users\alfre\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\deprecation.py)

In [ ]:
#Aplicamos la técnica de sobremuestreo (oversampling)
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

NameError: name 'SMOTE' is not defined

In [ ]:
#Entrenamos el modelo sobremuestreado
algoritmo_Over_sampling = LogisticRegression()
algoritmo_Over_sampling.fit(X_resampled, y_resampled)

In [ ]:
#Realizamos una predicción
y_pred_over_sampling = algoritmo_Over_sampling.predict(X_test) 
y_pred_over_sampling

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[386 753]
 [139 482]]


In [ ]:
#Calculo la precisión del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Astro")
print('Precisión del modelo:')
print(precision)

Precisión del modelo:
0.7518796992481203


In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred_over_sampling)
print('Exactitud del modelo:')
print(exactitud)

Exactitud del modelo:
0.5028409090909091


In [ ]:
#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Astro")
print('Sensibilidad del modelo:')
print(sensibilidad)

Sensibilidad del modelo:
0.34995625546806647
